window.botpressWebChat.init({
  botId: "d2038de9-8141-4e83-8ba9-52a07438048e",
  hostUrl: "https://cdn.botpress.cloud/webchat/v0",
  messagingUrl: "https://messaging.botpress.cloud",
  clientId: "d2038de9-8141-4e83-8ba9-52a07438048e",
  botName: "Aminoz",
  //   disableAnimations: true,
  avatarUrl: "https://api.iconify.design/bx/bot.svg",
  // "showBotInfoPage": true,
  enableConversationDeletion: false,
  showConversationsButton: false,
  enableTranscriptDownload: false,
  phoneNumber: "1300 264 669",
  emailAddress: "hello@aminoz.com.au",
  website: "https://www.aminoz.com.au/",
  stylesheet: "https://krisgodina.github.io/aminozstyle.css",
});
